### PR TITLE
add mailru graphite module

### PR DESCRIPTION
**Pull request by iamstarkov**

### CODE REVIEW

**Comment by iamstarkov** [comment]
very well maybe

**Comment by dvershinin** [comment]
Can you update your pull request with the correct soname, then I will
merge it.

**Comment by iamstarkov** [comment]
@dvershinin fixed

**Comment by dvershinin** [comment]
Interesting. Your metadata seems out of date. Because the corresponding module version has already been pushed to repos days ago. See https://extras.getpagespeed.com/redhat/7/x86_64/repoview/nginx-module-graphite.html

Or there's a versionlock?

**Comment by iamstarkov** [comment]
@dvershinin thank you, it was the billing issue and is fixed now. On this note, do you have a dedicated support communication means mail/slack/discord/etc?

**Pull request merged**
